name: ML Training Pipeline

# Trigger on pushes to any file under backend/src/ml or manual dispatch
on:
  push:
    paths:
      - 'backend/src/ml/**'
      - '.github/workflows/ml_training.yml'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install ML dependencies
      - name: Install dependencies
        working-directory: backend/src/ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Generate training data
      - name: Generate game data
        working-directory: backend/src/ml
        run: |
          node ../scripts/generate_game_data.ts

      # 5. Preprocess data
      - name: Preprocess data
        working-directory: backend/src/ml
        run: |
          python scripts/preprocess.py

      # 6. Train the policy network
      - name: Train model
        working-directory: backend/src/ml
        run: |
          python src/train.py --epochs 20 --batch-size 64

      # 7. Export for inference
      - name: Export to ONNX
        working-directory: backend/src/ml
        run: |
          python scripts/export_model.py

      # 8. Upload the trained models as workflow artifacts
      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: connect4-policy-model
          path: backend/src/ml/models/
